### ISSUE TITLE
After update from 0.6.2 to 0.6.3+, PF admin image does not start on OpenShift with error "sh: can't open './bootstrap.sh': Permission denied"

### ISSUE THREAD

**Issue by gsustek** [pingidentity/helm-charts#195]
After update from 0.6.2 to 0.6.3+, pf does not start with error "sh: can't open './bootstrap.sh': Permission denied" in openshift environment. Openshift environment by default has his own range of useruid to assign for running image.
Even if yaml file is populated with below values for runAsUser it seems that only userid 9031 has the ability to start ./bootstrap.sh script! 
Version 0.6.2 has this ability
Version from 0.6.3 and later does not have this ability to set arbitrary userid in /ets/passwd

####example of yaml file####
pingfederate-admin:
  enabled: true
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    defaultDomain: apps.projects.internal.local.com
    enabled: false
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
pingfederate-engine:
  enabled: true
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
global:
  workload:
    securityContext:
       runAsUser: 1002410000
       runAsGroup: 1002410000
       fsGroup: 1002410000
      # seLinuxOptions:
      #  level: 's0:c29,c9'
      #  level: 's0:c49,c29,c1,c2'     
      # allowPrivilegeEscalation: false
      #  capabilities:
      #  drop:
      #  - ALL

######################

Regards,
Goran.

**Comment by tsigle** [comment]
Thanks Goran,

When the helm-charts went to 0.6.3+ they are now using a sprint release 2105+.  In that release of the docker images, the ability to set a user/group was removed, which is affecting you.  Because this is related to a docker image issue, we'll close this issue.

There is an internal ticket that our DevOps team is working on to resolve this issue and look at options.  We would recommend that you raise a support ticket with Ping Identity against the docker image so we can communicate updates.  You can reference internal ticket, GDO-899 when you create you support case.

With respect to this specific case, you can set the default tag you run the helm-charts against to an earlier sprint release.  In this case you could use the value of:

```
global:
  image:
    tag: 2104
```

**Comment by gsustek** [comment]
Hi, 
Thnx for the additional information.

i could not post this issue on https://github.com/pingidentity/pingidentity-docker-builds because there is no "Issue" button and i could not also used     tag: 2104, becasue my devops license said, that i can not use three months old images with this devops license.

Regards,
Goran.

**Comment by tsigle** [comment]
Hi Goran,

Yea, we only use the getting-started github repo to accept issues related to everything devops.  I see that you posted this issue there, so that's appreciated.  We have added this to our internal ticket, and hope to get some feedback on this soon.

tls
